#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE

#=================================================

ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "scrutiny-web-server" >/dev/null
then
	ynh_script_progression "Removing scrutiny-web-server service integration..."
	yunohost service remove "scrutiny-web-server"
fi

if ynh_hide_warnings yunohost service status "scrutiny-collector" >/dev/null
then
	ynh_script_progression "Removing scrutiny-collector service integration..."
	yunohost service remove "scrutiny-collector"
fi

ynh_config_remove_systemd"scrutiny-web-server"
ynh_config_remove_systemd"scrutiny-collector"
ynh_safe_rm "/etc/systemd/system/scrutiny-collector.timer"

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
