#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================

ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if ynh_exec_warn_less yunohost service status "scrutiny-web-server" >/dev/null
then
	ynh_script_progression --message="Removing scrutiny-web-server service integration..." --weight=1
	yunohost service remove "scrutiny-web-server"
fi

if ynh_exec_warn_less yunohost service status "scrutiny-collector" >/dev/null
then
	ynh_script_progression --message="Removing scrutiny-collector service integration..." --weight=1
	yunohost service remove "scrutiny-collector"
fi

ynh_remove_systemd_config --service="scrutiny-web-server"
ynh_remove_systemd_config --service="scrutiny-collector"
ynh_secure_remove --file="/etc/systemd/system/scrutiny-collector.timer"

ynh_remove_nginx_config

ynh_remove_logrotate


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
